version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  dbseed: 
    build: ./seed
    env_file: .env
    depends_on:
      - db
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file: .env
